### ISSUE TITLE
issue #42 rises again: inputStream.read() causes occasional jtermios.windows.JTermiosImpl$Fail under 0.0.21

### ISSUE THREAD

**Issue by jason-s** [nyholku/purejavacomm#52]
I use purejavacomm 0.0.21 on Windows 7. I've been using it with the FTDI chip drivers. Works great.

Today I needed to use a USB to RS232 converter with a Prolific chipset rather than FTDI, and I am getting JTermiosImpl$Fail after a while. It's not a fatal error; if I retry the read it works fine. I'm getting this error maybe once every few minutes. This appears as though it might be the same issue as https://github.com/nyholku/purejavacomm/issues/42 .

```
jtermios.windows.JTermiosImpl$Fail
        at jtermios.windows.JTermiosImpl$Port.fail(JTermiosImpl.java:102)
        at jtermios.windows.JTermiosImpl.select(JTermiosImpl.java:900)
        at jtermios.JTermios.select(JTermios.java:439)
        at purejavacomm.PureJavaSerialPort$2.read(PureJavaSerialPort.java:886)
```

I am trying to get more information out of purejavacomm and it seems difficult. If I use 		

`jtermios.JTermios.JTermiosLogging.setLogLevel(4);`

it just spews messages continuously (I am reading from an embedded device at 625kbaud). I tried setLogLevel(2) and have been running for a half-hour without errors. Sounds like a Heisenbug.

Is there any way to record more information in the Exception itself without increasing the logging output under normal conditions?

**Comment by Lauchi** [comment]
I have got the same issue here but way more frequent, as I send a lot and in different threads. It occurs every 2-3 seconds. 
For me it is a little bit more dramatic, as I am writing a test program wich sends telegrams over the comports. If a telegram is missing, the testroutine fails :/
```
jtermios.windows.JTermiosImpl$Fail
	at jtermios.windows.JTermiosImpl$Port.fail(JTermiosImpl.java:102)
	at jtermios.windows.JTermiosImpl.select(JTermiosImpl.java:844)
	at jtermios.JTermios.select(JTermios.java:439)
	at purejavacomm.PureJavaSerialPort$2.read(PureJavaSerialPort.java:886)
	at purejavacomm.PureJavaSerialPort$2.read(PureJavaSerialPort.java:734)
	at Communication.TelegramReceiver.readInputStreamWithTimeout(TelegramReceiver.java:121)
	at Communication.TelegramReceiver.waitforTelegram(TelegramReceiver.java:46)
	at Communication.ComportThread.call(ComportThread.java:47)
	at Communication.ComportThread.call(ComportThread.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
java.io.IOException
	at purejavacomm.PureJavaSerialPort$2.read(PureJavaSerialPort.java:888)
	PAE Arrived, header: aa412292 700100 hardware: DiDoAi32, adress: 1, counter: 7, check: true, 
at purejavacomm.PureJavaSerialPort$2.read(PureJavaSerialPort.java:734)
	at Communication.TelegramReceiver.readInputStreamWithTimeout(TelegramReceiver.java:121)
	at Communication.TelegramReceiver.waitforTelegram(TelegramReceiver.java:46)
	at Communication.ComportThread.call(ComportThread.java:47)
	at Communication.ComportThread.call(ComportThread.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by nyholku** [comment]
Hi,

I'm rather busy atm, but I debugged privately (unfortunately) and there maybe a workaround that can be turned into a solution.

I will copy paste the discussion I had below, basically (if this is the same Invalid parameter error) what needs to happen is to re-try the offending call a few time. But please read the text below and see if you can try that. It will be some time before I have time to come back to this.

Dear Kusti Nyholm,

at first i want to thank you very much for the great library.

I was lookig for a serial communication library to adapt a java
application on a controller.
I like to develop in linux but the destination os is sometimes windows.

I use the newest version 0.0.22 of purejavacomm.
I work with the sourcecode (without the library jar) - so i can better
debug and also made some code adaptions for test cases.

If my app is running in windows, sometimes i get a "Fail" exception in
windows.JTermiosImpl.

In the case of the exception, some lines before

if (port.m_WaitPending) {
    if (!SetCommMask(port.m_Comm, 0))
        port.fail();
    GetOverlappedResult(port.m_Comm, port.m_SelOVL, port.m_SelN, false);
    port.m_WaitPending = false;
}
the GetOverlappedResult function results with false. I test there with
GetLastError and get a 996 (ERROR_IO_INCOMPLETE).

I think, this condition let produce in the next call of WaitCommEvent
the error 87 (The parameter is incorrect).

Do you have somme time to help for solving the problem?

It would be very nice, if i get a answer from you.

Thank you very much,
best regards,
Jens Rueckert

p.s.
please excuse my bad english, i'm german


Hi Jens,

you've unfortunately stumbled an latent bug that I've not been able
trace as it does not happen in my test environment.

Basically what happens is that my code tries to re-use the
port.m_SelOVL object because creating a new one is an expensive
process and slows down the system. And not only that,
creating a new object every time creates a storage
allocation problem because we can't discard objects
that are being used by the OS before the OS has
finished with them so we can't leave this to the
garbage collector).

So, sometimes the IO operation associated with port.m_SelOVL
has not yet completed so an attempt to re-use it causes
"87 the parameter is incorrect". The code tries to handle
this but obviously it does not succeed in that. IIRC the
m_WaitPending flag was created just for that purpose.

So that is the root cause of the problem.

My current thinking is that maybe the code should just
re-try the call that fails as long it gets the error 87
because the IO should complete pretty soon anyway
and after that the re-use should succeed.

So do something like

do {
  // here the call that fails with err 87
} while getLastError()==87;

I don't have access to source code right know so
I can't pin point you exactly where you should do
this but you get the idea.

It would be great if you could fix this problem!

br Kusti


Hi Kusti,

because I don't understand your code in detail, I test two
versions (please see in the attached file JTermiosImpl.java
the section "Test (1)" and "(2)").

In the first version I check the GetOverlappedResult() for
the ERROR_IO_INCOMPLETE status.
In this case, so I think, we add the port to the waiting list,
break the next steps and try later a new GetOverlappedResult().
Can you explain, why this version doesnt works safe? (log2.txt)

In the second version I call GetOverlappedResult() repeatly
until it returns without ERROR_IO_INCOMPLETE.
For the case of infinite calls is there a counter.
This seems reliable working - sometimes the loop run for one
time very seldom for two times.
Can you logical check the workaround?
And if the solution o.k. - when did you think you can release
a new lib version?

Thank you very much,
best regards,
Jens

Hi Jens,

thanks for the great work on debugging this.

Looking at the code (ie without running it) test 1 probably
fails because you break the loop with 'continue' so although
the port is added to the list of waiting ports you skip
all the code that actually makes the port to wait, especially
the WaitCommEvent, and you can't execute that code because
the previous WaitCommEvent is still no complete. My original
and failed attempt tried to force the WaitCommEvent to complete.

Test 2 works because it actually waits for the previous pending
WaitCommEvent to clear.

I'm not 100% happy with your code as it stands so I'm not ready
to incorporate it to my repo yet.

The main issue is the sleep(1) ... this introduces 1 msec delay
every time there is a pending event happening there and this
may limit the performance of the communication under certain
situations, we should never use sleep() to wait for something.

I think the correct way to handle this is that we should use
the WaitForMultiple objects pattern (see a little bit further
down in the select() method code). This should wait until
the pending event clears itself OR the cancel event happens.
Make a note of how the cancel event as this all this needs
repeat here too. So you need something like:

    HANDLE[] wobj = new HANDLE[2];

    wobj[0] = port.m_SelOVL.hEvent;
    wobj[1] = port.WaitCommEventCancelObject;
                        }
    int tout = timeout != null ? (int) (timeout.tv_sec * 1000 + timeout.tv_usec / 1000) : INFINITE;
                       
    int res = WaitForMultipleObjects( 2, wobj, false, tout);

if (res == WAIT_TIMEOUT)
    return 0;

else {
    i = (res - WAIT_OBJECT_0) ;

    if (i == 1)
        // it was the cancel sema4 so just return
        return 0;
        fail();
    }

Note that now the 'tout' is computed in two places in the
code which is not cool so this should be moved somewhere
so that there is Single Point of Truth.

A couple of thoughts:

I'm not sure if it would be enough just to use the
WaitForMultipleObjecst here and leave the WaitCommEventOut,
might be worth a try.

Also is this the place where the 'invalid parameter' error
happened in the first place ... my idea originally, when
you reported this problem, was that we should try to do
all this waiting stuff only if we get the invalid parameter
because this would allow us the get rid of the m_WaitPending
flag altogether and probably the code would be more
efficient as we would do all this waiting stuff only
when it necessary. I maybe wrong there but that was
my idea.

One more side note.

I'm fine with discussing this over the email like we
are doing her but for the sake of the community it would
be better to do this in the github. And the 'correct'
way to work on the code would be for you to fork the repo
in github because then all the diff tools would work
for us. You can easily also create several branches there
to try different scenarios.

br Kusti

**Comment by nyholku** [comment]
Closing this as I've not heard back from this issue -- feel free to re-open

**Comment by bmeierh** [comment]
Just tried purejavacomm 1.0.0 with JNA 4.2.2 and got the same error. The reason for this problem can be found in this mailing list jna.dev.java.narkive.com/y4xjiFGC/windows-jna-overlapped-io-passing-the-same-memory-area-two-all-calls. I changed the method definiton in the WinAPI class from public boolean GetOverlappedResult(HANDLE hFile, OVERLAPPED lpOverlapped, int[] lpNumberOfBytesTransferred, boolean bWait); to public boolean GetOverlappedResult(HANDLE hFile, Pointer lpOverlapped, int[] lpNumberOfBytesTransferred, boolean bWait);  and the method invocation to res = m_K32lib.GetOverlappedResult(hFile, ovl.getPointer(), ntfrd, wait); and the problem seems to  be fixed. 		
Kind Regards
Bernd
