### ISSUE TITLE
How to find port is already in used.

### ISSUE THREAD

**Issue by ReeganArockiasmy** [nyholku/purejavacomm#54]
I have used pure java comm api in my serial port project.I have open port in minicom, now open port via pure comm api.but port in use exception not throw, how to find port in already in use

**Comment by johnstosh** [comment]
Hi Reegan,

Interesting question.  my experience has been that if the port is in use,
then you won't be able to open it.
I'm using Putty for a dumb terminal, to open a serial port. When Putty has
the port open, then I can't open it with any other program.

As a separate issue, notice that when a USB serial port device is unplugged
(and then plugged back in) then you apparently don't get an exception or
any error from windows. So close the port and re-open it and then data
moves again.
Interesting to note that windows once in a while just looses the connection
to a USB device. When that happens, it seems to be the same as unplugging
the device and plugging it back in.

Kind Regards,
Johnny


--
Johnny Muczynski
734-262-2045

**Comment by axvr** [comment]
Hi, I don't think this issue was resolved as I've encountered this exact problem on my machine (Fedora Linux 35).

PureJavaComm won't throw a `PortInUseException` if the serial port is in use by another program (such as Picocom or GNU Screen).  The `isCurrentlyOwned` method on `CommPortIdentifier` still returns `false` when the port was opened by an external program.

(I've also noticed that the port isn't properly locked as external programs can still connect to the port even after PureJavaComm has opened it.)
