### ISSUE TITLE
Port Disconnect exception in windows

### ISSUE THREAD

**Issue by ReeganArockiasmy** [nyholku/purejavacomm#71]
I have write a code in serial port,  is working on Linux as well as windows. it is common code for both machine, 

problems:-
-------------

 1. I have disconnect the device in Linux i will get IO Exception.

 2 . I have disconnect the device in Window i will get error message in (version 0.0.22)
        jtermios.windows.JTermiosImpl$Fail
        at jtermios.windows.JTermiosImpl$Port.fail(JTermiosImpl.java:102)
        at jtermios.windows.JTermiosImpl.clearCommErrors(JTermiosImpl.java:776)
        at jtermios.windows.JTermiosImpl.select(JTermiosImpl.java:872)
        at jtermios.JTermios.select(JTermios.java:439)
        at purejavacomm.PureJavaSerialPort$3.run(PureJavaSerialPort.java:1226)
        at java.lang.Thread.run(Unknown Source)

and also get this type of error (version 0.0.26)

Exception in thread "COM5" com.sun.jna.LastErrorException: [995] The I/O operati
on has been aborted because of either a thread exit or an application request.
        at jtermios.windows.WinAPI$Windows_kernel32_lib_Direct.GetOverlappedResu
lt(Native Method)
        at jtermios.windows.WinAPI.GetOverlappedResult(WinAPI.java:779)
        at jtermios.windows.JTermiosImpl.select(JTermiosImpl.java:937)
        at jtermios.JTermios.select(JTermios.java:467)
        at purejavacomm.PureJavaSerialPort$3.run(PureJavaSerialPort.java:1222)
        at java.lang.Thread.run(Unknown Source)

how to handle this error.

**Comment by PeteSL** [comment]
And the same will be true with 0.0.27.  select() in Windows does not throw an IOException as Fail is not an IOException.  This is a good point for consistency across platforms; if the base design is to throw an exception of a certain type (in this case, an IOException), that should be carried through to all platforms including Windows.

**Comment by nyholku** [comment]
@PeteSL yes, I agree with this.

**Comment by PeteSL** [comment]
@nyholku Of course, the problem is identifying where an IOException is passed through elsewhere and making it the same throughout (probably should identify in the JTermioImpl Interface definition).  Not an easy task and the simple answer initially is catch Exception, not just IOException until the those situations can be identified.

**Comment by PeteSL** [comment]
Yes, probably should be an IOException.  It will likely be some time before the Windows code is fully compared to the reset of the implementations (note a number FIX comments in the Windows source regarding translating errors which would probably address this).  In the mean time, if you catch Exception instead of IOException, you will probably be good until the Windows code is updated to match the other implementations.

**Comment by nyholku** [comment]
Looking again at the original stack trace this is actually the internal PJC thread that crashes because the device disappears.

So the OP cannot catch this exception and the stack trace is coming from the Thread class I presume.

Thinking further, this should not happen with latest code because select() (or any other JTermios method) should never thrown an exception but return an error code.
