### ISSUE TITLE
issue #52 rises again: jtermios.windows.JTermiosImpl under 1.0.0 causes 996 (ERROR_IO_INCOMPLETE) #83

### ISSUE THREAD

**Issue by bmeierh** [nyholku/purejavacomm#83]
Reason/Solution can be found in my comment to issue #52

**Comment by nyholku** [comment]
I just pushed the changes:

https://github.com/nyholku/purejavacomm/blob/master/src/jtermios/JTermios.java

can you please test that, I don¨t have working Windows setup with serial port atm. 

If it works I will make a proper release.

br Kusti

**Comment by bmeierh** [comment]
I changed the following files and now it works smooth on Windows with JNA 4.2.2
[windows.zip](https://github.com/nyholku/purejavacomm/files/262807/windows.zip)
Kind Regards,
Bernd

**Comment by nyholku** [comment]
Can you just post the diff or preferably do this on github and create pull request ... working with files is a chore...

**Comment by bmeierh** [comment]
Hi, my changes are now comitted to the fork bmeierh/purejavacomm. These are my first code changes on GitHub. Please be patient with me and sorry if I did something wrong. 
Kind Regards,
Bernd

**Comment by nyholku** [comment]
Hi, thanks for that but you've made quite a lot changes (360 additions and 114 deletions) and a lot of white space changes so it is next to impossible to reliably see what is relevant and what is not. 

Please start afresh and make *minimal* changes that are necessary to make it work and don't allow your IDE to mess up the formatting of the source files. Don't spell out the imports etc, don't delete functions you think are not necessary, just make the changes that are necessary to make the code work so I can see what is the problem with my code.

Thanks.

**Comment by bmeierh** [comment]
Hi, now only the _minimal_ changes are committed. I changed my IDE not to organize the imports and not to add the @Override annotations. Nevertheless I think using some static code analysis tool (e.g. FindBugs) will be a good idea to find such errors:

```
JTermiosImpl.java:717, RV_EXCEPTION_NOT_THROWN, Priorität: Hoch

RV: new RuntimeException(String) not thrown in jtermios.windows.JTermiosImpl.write(int, byte[], int)

This code creates an exception (or error) object, but doesn't do anything with it. For example, something like

    if (x < 0)
      new IllegalArgumentException("x must be nonnegative");

It was probably the intent of the programmer to throw the created exception:

    if (x < 0)
      throw new IllegalArgumentException("x must be nonnegative");
```
Kind Regards,
Bernd

**Comment by nyholku** [comment]
Sure, static code analysis tools are good. At least up to a point. Like the example you gave, this most likely an error (would have to be a really bizarre 'IllegalArgumentException' constructor if it threw something useful ;)

But I fail to see the connection here. You/we have a clearly a problem and most likely a solution, and we want to apply that, and only that, cleanly to the codebase so that we see what is going on. 

If you/we want to do some other bug fixes we should do them as one or more separate issues. Preferably more than one if there are more than one type of issues. Otherwise changes get easily rejected, some people have done big reorganisation of the codebase to please themselves and because part of the changes are not something I agree with they get rejected. Better have small changes to have a better chance of getting them accepted.

For example: I like adding @Override but I do not like having separate import for each and every class. So these changes are lumped together the changes will get rejected. 

(As an asside 'import everything individually', I don't agree with that policy because very, very seldom have I seen  in my +15 year Java career a problem with 'import *' where as every time my IDE does 'import somepackage.someclass' in the next few minutes an other import is needed of the same package is needed so it is annoying waste of time).

**Comment by bmeierh** [comment]
Hi, I totally agree with you. I see the problem if my commit contains further changes. Sorry!!! With my last commit only the necessary changes in the select(int, FDSet, FDSet, FDSet, TimeVal) method are included. In addition to the OVERLAPPED pointer the following code changes are necessary:

Line 847 -old:
`GetOverlappedResult(port.m_Comm, port.m_SelOVL, port.m_SelN, false);`

Line 847 -new:
```
if (!GetOverlappedResult(port.m_Comm, port.m_SelOVL, port.m_SelN, false)) {
   int lastError = GetLastError();
   if (lastError != ERROR_IO_INCOMPLETE) {
      port.fail();
   }
}
```
The Windows documentation says, that in case of a negative result, the GetLastError method always has to be called.

Line 876 -old:
```
if (GetLastError() != ERROR_IO_PENDING) 
   port.fail()
```

Line 876 -new:
```
int lastError = GetLastError();
// Under Windows sometimes the error code 87 (ERROR_INVALID_PARAMETER) is returned.
// I have not investigated why, but it is also a valid reply
if (lastError != ERROR_IO_PENDING && lastError != 87) {
  port.fail();
}
```

**Comment by bmeierh** [comment]
Hi, will you add this changes?
Kind Regards,
Bernd

**Comment by nyholku** [comment]
Hi, I've added the changes but:
1) I have no working Windows setup with a serial port so I cannot test this
2) Even when I did, I never saw this error so could not test it anyway
3) Not sure I changed the correct lines as the line numbers did not match mine,
your code was probably not virgin from github when you made the changes.

So please test, I will not make a release before I hear back from you.

For the future, please 'diff' against the github code to produce patches or,
preferably, clone the repo and create a pull request, that is the github
workflow way of doing things.

And many thanks for contributing.

**Comment by bmeierh** [comment]
Hi, Thank you for the changes! I did some testing (with JNA 4.2.2 and your new code) and had no problems anymore. In the future I will act on your advice. But as already mentioned I'm an absolut github novice. 
I don't want to be pushy but published releases (e.g. Maven Central) would be great (refer to issue#82). What is your intention?
Kind Regards,
Bernd

**Comment by nyholku** [comment]
Hi, thanks for the report. I will try to do a release within a week or two.

As to maven central, I looked at the process and while pretty straightforward on the face of it my experience tells me it will take a good afternoon and then some iteration to get it to work and can't prioritise that time usage atm. So yes, but not now.
