### ISSUE TITLE
Behaviour of closing port on one thread while reading from inputstream on a different thread

### ISSUE THREAD

**Issue by bondolo** [nyholku/purejavacomm#89]
There are issues with being able to close a comm port while some other thread is reading from the inputstream. It is a common pattern to have a dedicated thread processing input asynchronously while the system carries on on different threads.

Currently, depending on timing, closing a port might result in the read() returning -1, throwing IllegalStateException, or throwing IOException. Ideally all would just return -1.

**Comment by bondolo** [comment]
ping!

**Comment by derikd** [comment]
On Jun 14, 2016, at 11:19 AM, Mike Duigou <notifications@github.com<mailto:notifications@github.com>> wrote:


There are issues with being able to close a serial port while some other thread is reading from the inputstream. It is a common pattern to have a dedicated thread processing input asynchronously while the system carries on on different threads.

Currently, depending on timing closing a port might result in the read() returning -1, throwing IllegalStateException, or throwing IOException. Ideally all would just return -1.

I do agree it should always return the same value/exception regardless of the timing.
I further agree that throwing IllegalStateException is undocumented, and if it can be avoided I would rather PJC didn’t do that.

But if the OS closes your port because the user unplugged the USB/Serial adapter, then that seems “exceptional” to me.   It means that you have reached the end of the “file”, but it also means more than that.   In a similar way if another thread closes the port, releasing your streams resources back to the OS, than that is an exceptional condition.

Having said that, it seems there is no reliable way to interrupt a read() method except by closing the port, so maybe there is nothing exceptional about doing it that way.

—
derik


----------------------------------------------
P.S.   JaveDoc for InputStream is below.





The JavaDoc for Input stream says the following.

public abstract int read()
                  throws IOException
Reads the next byte of data from the input stream. The value byte is returned as an int in the range 0 to 255. If no byte is available because the end of the stream has been reached, the value -1 is returned. This method blocks until input data is available, the end of the stream is detected, or an exception is thrown.
A subclass must provide an implementation of this method.
Returns:
the next byte of data, or -1 if the end of the stream is reached.
Throws:
IOException - if an I/O error occurs.





The JavaDoc for InpustStream doesn’t specify what happens when another thread closes the input stream.

**Comment by nyholku** [comment]
Hi, sorry it has been a while. 

It would be helpful if you had stack trace of the IllegalStateException or IOException, the read code is pretty complex and I don't want to touch it more than I have to.

**Comment by duyngq** [comment]
Hi All,

I'm facing the same issue when restarting the application that is running on Serial port while another thread is waiting the input from user. And here is the stack trace I got:

purejavacomm.PureJavaIllegalStateException: File descriptor is -1 < 0, maybe closed by previous error condition
	at purejavacomm.PureJavaSerialPort.failWithIllegalStateException(PureJavaSerialPort.java:1266)
	at purejavacomm.PureJavaSerialPort.checkState(PureJavaSerialPort.java:1271)
	at purejavacomm.PureJavaSerialPort.access$0(PureJavaSerialPort.java:1269)
	at purejavacomm.PureJavaSerialPort$2.read(PureJavaSerialPort.java:712)

From what I see, thought the issue from PureJavaSerialPort::close(), after closing, the m_FD var will be -1. In the mean time, the read method from input stream is reading, so check state check and throw exception. But the question here is: why do we have a bunch of error log.

If you need any more info, please let me know.

**Comment by bondolo** [comment]
The pull request I have submitted makes the PureJavaSerialPort InputStream behave more like a Java Socket InputStream. Specifically EOF conditions are handled by returning -1 rather than throwing Exceptions. The implementation doesn't make an effort to distinguish error close from normal close. If the close reason was distinguished then some of the exception cases could return.

**Comment by nyholku** [comment]
Hi, I've not had time to look at the patch but in my view, because of the complexity of the read code, it would be best to catch all exceptions and return -1 in that case. This would be consistent with the InputStream behaviour, in retrospect it is I think it is wrong to throw any exceptions not specified in the InputStream spec. 
~~~
IOException - If the first byte cannot be read for any reason other than end of file, or if the input stream has been closed, or if some other I/O error occurs.
NullPointerException - If b is null.
IndexOutOfBoundsException - If off is negative, len is negative, or len is greater than b.length - off

From InputStream spec:

~~~
If and when we revisit we should fix this once and for all.

In fact I seem to remember to writing this sort of patch at some point, I will need to check that.

Like I said I've not had time to look at your code so maybe it takes care of all this properly.

cheers Kusti

**Comment by sfeuerhahn** [comment]
I believe the InputStream should behave similar to the Java Socket InputStream.

The Java socket InputStream.read() method has the following behavior:

- TCP connection is closed by remote host:
returns -1
- TCP socket is closed by other thread:
throws java.net.SocketException (a special IOException)
- A socket timeout occurs:
 throws java.net.SocketTimeoutException (a special InterruptedIOException)

The case that the remote host closes the stream is not a scenario which applies for serial communication. Thus I actually believe the serial InputStream should never return -1. Instead I would suggest the following behavior:

- serial port is closed by different thread:
throws SerialPortException (a special IOException)
- serial port vanishes (e.g. an usb-serial device is unplugged):
also throws SerialPortException (a special IOException)
- A timeout occurs:
SerialPortTimeoutException (a special InterruptedIOException)

This way socket and serial streams would behave identically.

This is the behavior we aim for with our wrapper of RXTX (https://github.com/openmuc/jrxtx). But your project looks much more promising than RXTX!!

**Comment by nyholku** [comment]
Conflicting requirements! 

Looks like Sun (Oracle) is not bound by its own spec, like this has never happened before ;)

Logically the InputStream spec should be honoured. But on n:th reading I now have doubts about what it means when it says:

"[throws IOException] If the first byte cannot be read for any reason other than end of file, 
or if the input stream has been closed, or if some other I/O error occurs."

Does that mean that -1 should be returned if the input stream has been closed. That was my previous interpretation, I'm now hesitating a bit. I guess that can and perhaps should be read that -1 is only thrown if end of file has been reached and IOException in any other case. 

So it comes down to if a closed port is 'eof' or not. 

If the intention is that serial port input stream could be used to feed code that only expects InputStream behaviour then I guess the most practical solution is to return -1 when the port is closed, throwing an exception is most likely something that code designed to work with InputStream is not prepared to handle.

As PureJavaComm aims to be RXTX replacement it sort of dictates following that spec, OTH RXTX is supposed to be JavaComm replacement so this rises the question what did JavaComm do in its hay day.

Yet again, I'm not 100% sure it is possible to reliably detect under all conditions and all operating systems that a port has been closed in an other thread  and return -1.

Decisions, decisions...

**Comment by sfeuerhahn** [comment]
I agree the decision comes down to the question whether closing the port results in EOF (i.e. -1) or an Exception. Since the InputStream class is not clear about this I would suggest to copy the Socket InputStream behavior.

We have used RXTX extensively in our projects so I know its behavior:

- the serial port's close() function blocks if another thread is blocking in a read() method. Thus with RXTX it is not possible to interrupt a blocking read() by closing the serial port.

- When a timeout occurs it does not throw a TimeoutException but returns -1

In my opinion this behavior is very inconvenient for programmers. May be you should give up on the goal to be drop-in replacement of RXTX and instead make a beautiful API? :-)

**Comment by nyholku** [comment]
Thanks for the info on RXTX.

At the moment I'm ready to throw IOException (or some sub class) from read if the port is closed by an other thread. 

As to timeout, I think this clearly spelled out in JavaComm spec and should not throw timeout.

In regards to making a beautiful API my thinking is that is should be either a wrapper around PureJavaComm  or maybe better yet a separate project from ground up picking implementation details from PureJavaComm. 

The lessons learned from PureJavaComm is that the model I chose (emulating Unix style IO in Windows) is probably not the best and also that the constrains that JavaComm API spec puts onto the implementation are not the best. 

So separate clean start might lead to a better API and internal structure.

But PureJavaComm should stay more or less the same as it serves a definite purpose for many people who relay on JavaComm behaviour.

**Comment by nyholku** [comment]
I've now changed the PureJavaSerialPort input stream to throw IOException if the port is closed. Will be in the next release.
