### ISSUE TITLE
Serial port does not return from select method under MacOSX

### ISSUE THREAD

**Issue by tkutz** [nyholku/purejavacomm#93]
I observe different behavior in MacOSX and Windows for the `select` call in `PureJavaSerialPort` line 1223 (sources from current 1.0.1 release).

In Windows the call returns and the outer while loop goes on, while on MacOSX (10.9.5) the thread stays in the native call and does not return. The result is the following: When I disconnect my device from USB, the native `select` call returns, however the serial port still thinks that it needs to send an event (line 1241). In my event listener, I check for `serialPort.getInputStream().available()` which throws an `IOException` (line 721). 
I think this behavior is not correct. Plugging out a device should not result in Exceptions popping up in my client code; especially when it works perfectly for Windows.

If this appears to be not a bug in purejavacomm, it would be nice to know what the underlying problem is.

**Comment by nyholku** [comment]
I will be busy for a week or two and can't really dig into this.

My knee jerk reaction is that un-pluggin a USB port is undefined in its consequences.

When all this serial port stuff was defined back all those decades ago it was not possible for a serial port to disappear. Hence the OS APIs don't handle this well and it is hard to handle this nicely.

Basically any PJC API call may throw an exception in these circumstances. To make it not-throw maybe quite a long road as there really is not a reliable mechanism to detect the unplug *before* bad things happen so may OS calls will return IO errors or what not in such a circumstance.

In the short term your best bet is to capture any exceptions and treat these cases as 'port un-plugged'. 

The fact that it appears to behave better in Windows is likely just a fluke and just *appears* to behave better likely to behave just as badly under slightly different conditions.

best Kusti

**Comment by tkutz** [comment]
Thanks for the fast reply!

The exception is only a side effect, because the call into `select` method does not return on MacOSX, only after device gets unplugged, but then the state of serial port is invalid which leads to an event being sent. I don't think it is correct to send an event that pretends there is some data to be read, when a device gets un-plugged.

So from my point of view it is not the OS specific handling of un-plugging, but the different behavior of `select` method, which as a side effect results in an exception when devices get un-plugged. Probably this has also further side-effects, but for my use cases this is the only one I noticed.

**Comment by nyholku** [comment]
I see. It is a bit of a problem on if select() on Mac does not return, as it is a native OS API call. Only way to fix this is to have a timeout, which is not nice as it is in effect polling or listening to the device removal events and then 'nudge' the select with a local 'nudge' pipe so that it will return. The later approach is much more complex (though I've been through that one with my PureJavaHidApi project) but logically better. I try to remember to look at this when I return from travelling.

**Comment by nyholku** [comment]
I've now looked into this and I think that it valid and best approach to throw IOException from available() in this circumstance. As the spec for available() say it can throw an IOException the client code needs to be prepared to handle this. Unplugging USB devices is a problematic thing because way back in history when a lot of this was specified there was no such thing as unplugging devices from a running machine.
